### ISSUE TITLE
Nightstand clock null pointer dereference

### ISSUE THREAD

**Issue by Lecker-Duplo** [ClaraCrazy/Flipper-Xtreme#140] opened 2023-02-17 17:51 UTC
Starting the clock (short press courser left on homescreen) sometimes causes the device to crash/reboot.
Error message:
null pointer dereference

**Comment by Willy-JL** [comment] 2023-02-22 20:40
We had it happen just a couple times but it is very rare and we struggle to reproduce it... we will try to look into it but can't promise anything

**Comment by ClaraCrazy** [comment] 2023-03-09 20:00
@Lecker-Duplo havent seen it happen in a while. we did lots of changes since then to the code. can you confirm the issue is gone?

**Comment by Lecker-Duplo** [comment] 2023-03-09 21:42
I have just updated to the latest version.
Unfortunately, the problem still occurs. Sporadically, but it does occur.
Maybe it has something to do with the 24h D/M/Y metric.
As a test I have set the time and date format to 12h M/D/Y and there the problem does not seem to occur.... at least until now.

**Comment by m0rd3cai** [comment] 2023-03-17 18:02
I can confirm I just put the March 9th release on a clean Flipper and it has done this twice now in 15-20 minutes. Will update if it starts doing it again. It appears to have stopped for now. Will update. This is a new Flipper, not a dev flipper.

**Comment by Willy-JL** [comment] 2023-04-06 01:22
Should now be fixed via 4af2bd01ef6908d2417102e0f7a9fa63e8c142d2, haven't been able to replicate it anymore after that fix. Looks like it was a race condition, the draw callback needed the display brightness, but that was set after the the draw callback, so occasionally it would read the data before being set. Can you please verify if the issue is fixed in the [dev build](https://github.com/ClaraCrazy/Flipper-Xtreme/actions/runs/4624431401)?

**Comment by Lecker-Duplo** [comment] 2023-04-08 11:42
Solved with XFW-0043_28032023

**Comment by ClaraCrazy** [comment] 2023-04-09 19:19
Fixed in latest release

**Closed by ClaraCrazy** 2023-04-09 19:19 UTC
Labels: bug, release-pending
